project:
  type: website
  output-dir: docs

website:
  title: "BIOST2041"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/https://github.com/haleykgrant/BIOST2041

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

