project:
  type: website
  output-dir: docs
website:
  title: Intro Biostatistics Resources
  reader-mode: true
  repo-url: https://github.com/haleykgrant/IntroBiostatResources
  sidebar:
    style: "floating"
    search: true
  navbar:
    right:
    - about.qmd
    - icon: github
      href: https://github.com/haleykgrant/IntroBiostatResources
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    include-after-body: include/webex.js
editor: visual
